### ISSUE TITLE
How can I use it to predict elastic properties for 2D systems

### ISSUE THREAD

**Issue by kcbhamu** [gmp007/2D_Elastic-Properties#1]
Hii,

I have used elastool package but I wonder, how can I use this tool to predict elastic properties for 2D systems.

Thanks

**Comment by gmp007** [comment]
Hi,
We have example folder in the ElasTool GitHub that shows how to
calculate the elastic constant for 2D materials at
https://github.com/zhongliliu/elastool. Let me know if you have any
questions.
*Yours Sincerely,*
Chinedu Ekuma, PhD
Department of Physics
Lehigh University
16 Memorial Drive East
Bethlehem, PA 18015
Phone: (610)-758-6428; Fax: (610)-758-5730

Website: http://www.cekuma.com

*The joy of discovery is certainly t**he liveliest that the mind of man can
ever feel*

**Comment by kcbhamu** [comment]
Thanks Prof. Ekuma,
I have finished calculations with elastool. I was asking for this "2D_Elastic-Properties" package.
Regards

**Comment by gmp007** [comment]
We developed the ElasTool code, which is what we used in the calculation
for the 2D elastic constants.

*Yours Sincerely,*
Chinedu Ekuma, PhD
Department of Physics
Lehigh University
16 Memorial Drive East
Bethlehem, PA 18015
Phone: (610)-758-6428; Fax: (610)-758-5730

Website: http://www.cekuma.com

*The joy of discovery is certainly t**he liveliest that the mind of man can
ever feel*
